# Generated by Django 4.0.4 on 2022-06-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_comment_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='categoy',
            new_name='category',
        ),
    ]
