# Generated by Django 4.0.4 on 2022-07-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
